### ISSUE TITLE
poetry run pytest /test throws ModuleNotFoundError no module named "example"

### ISSUE THREAD

**Issue by michealroberts** [DavidVujic/python-polylith-example#11] opened 2024-03-13 16:25 UTC
Following through from this example repository, and in other projects, I am seeing this error when running tests with poetry:

```bash
poetry run pytest test/
```

It gives this error:

```
ModuleNotFoundError: No module named 'example' 
```

As far as I can see, there is nothing up here. However, any pro-tips as to where I have gone wrong would be amazing.

I have created my components with the `poetry poly create` command as documented ...

**Comment by DavidVujic** [comment] 2024-03-13 17:39
Could it be that you haven't set up the virtual environment?

Run `poetry install` to add all third-party dependencies (and to make Poetry recognize the folder structure of the repo).

Then you should be able to run `poetry run pytest` and the Polylith commands, such as `poetry poly info`.

**Comment by michealroberts** [comment] 2024-03-13 17:50
@DavidVujic So I have run the usually `poetry init`, `poetry shell` and `poetry install` commands.

I have no issue running `poetry run mypy .` or `poetry poly` commands, this seems to be the only one that is failing ...

**Comment by michealroberts** [comment] 2024-03-13 17:51
As an example:

![CleanShot 2024-03-13 at 17 51 07](https://github.com/DavidVujic/python-polylith-example/assets/84131395/f9c240d4-71e3-4a74-9aa5-6290b6a16070)

**Comment by DavidVujic** [comment] 2024-03-13 18:04
My guess is that you have MyPy and pytest installed globally, otherwise the command would fail on "pytest". So, for pytest to be able to run code, that in turn might use third-party libraries, you need to have a virtual environment. That is created by using the `poetry install` command (only needed once). You will then have a `.venv` folder along the other folders at your repo root.

The reason that the `poly` commands work is that you have the Polylith plugin installed globally too - globally, as in where Poetry stores its own dependencies.

**Comment by michealroberts** [comment] 2024-03-13 18:09
Hi @DavidVujic Unfortunately none of that accurately describes my environment, I do not have mypy or pytest installed globally. I develop inside the poetry environment, and have installed all dependencies.

![CleanShot 2024-03-13 at 18 06 59](https://github.com/DavidVujic/python-polylith-example/assets/84131395/9a147a4d-6ab5-4a6e-be83-ca365bd511c7)

I have also installed the two poetry plugins and developer dependencies inside the environment, and not globally. As I develop inside a containerised environment (for portability within our team).

**Comment by michealroberts** [comment] 2024-03-13 18:10
Here is my repository structure with .venv visible:

![CleanShot 2024-03-13 at 18 09 26](https://github.com/DavidVujic/python-polylith-example/assets/84131395/68667c40-a83f-426f-b043-40723f117561)

Could the issue be in the installed versions of pytest? I see the repo example has version 7, and I have version 8.*.* ...? 🤔

**Comment by michealroberts** [comment] 2024-03-13 18:13
Maybe we could jump on a call? 📞

**Comment by DavidVujic** [comment] 2024-03-13 18:15
Could you share the contents of the pyproject.toml file (the `packages` section in particular), and the contents of the workspace.toml file?

**Comment by DavidVujic** [comment] 2024-03-13 18:26
From looking at your screenshot from the `poly info` command, it looks like the components aren't added to the pyproject.toml at the root? That would explain why pytest cannot locate the namespace. The components and bases need to be added in the `packages` section, for Poetry to recognize them in the virtual environment.

**Comment by DavidVujic** [comment] 2024-03-13 18:26
docs here: https://davidvujic.github.io/python-polylith-docs/projects/ 

(the docs show bricks for projects. The root pyproject would be the same, but without the relative `..` paths)

Here's how it is setup in the example project (where`example` is the top namespace): https://github.com/DavidVujic/python-polylith-example/blob/main/pyproject.toml#L8

**Comment by michealroberts** [comment] 2024-03-14 09:18
Ok, I have had a little think and a review of everything we do ... I have tried both poetry from a .venv and globally installed inside the container, neither seem to work with this polylithic structure and pytest.

Everything else seems to work, mypy, ruff etc etc

I can see however, inside the test/ folder, the tests that I have aren't showing any types ...

I haven't even got to installing projects or bases yet, so at the moment I just have components as tester to see if this all works well.

RE: `poly info` command, the components are added to the root pyproject.toml file as follows:

```toml
[tool.poetry]
name = "observatory"
version = "0.1.0"
description = "Spaceflux's telescope control system monorepo for managing their global sensor network of astronomical observatories."
authors = ["Michael Roberts <michael.roberts@spaceflux.io>"]
readme = "README.md"

packages = [
  { include = "observatory/astrometry", from = "components" },
  { include = "observatory/common", from = "components" },
  { include = "development" },
]

[tool.poetry.dependencies]
python = "^3.12"
poetry-multiproject-plugin = "^1.4.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.2"
pre-commit = "^3.6.2"
pytest = "^8.1.1"
poetry-multiproject-plugin = "^1.4.1"
poetry-polylith-plugin = "^1.17.2"
mypy = "^1.9.0"

[tool.pytest.ini_options]
addopts = "-vv"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

I feel like I have absolutely followed everything by the letter, it's clearly to do with module discovery ...

We are using pytest version 8 and python 3.12 ...

**Comment by michealroberts** [comment] 2024-03-14 09:19
This is our Dockerfile:

```
# Copyright © observerly Ltd

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

# Base Python Image
FROM python:3.12-bullseye AS base

RUN ["apt-get", "update"]

# Set the working directory, i.e., the directory within the container where the commands will be executed:
WORKDIR /usr/src/app

# Set the PYTHONPATH environment variable:
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

# As we are containerising our application, we do not want to write .pyc files: 
ENV PYTHONDONTWRITEBYTECODE 1
# Ensure we do not buffer our console output, e.g., forcing the stdout and stderr streams to be unbuffered
# for easier container logging
ENV PYTHONUNBUFFERED 1

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
  cd /usr/local/bin && \
  ln -s /opt/poetry/bin/poetry

# As we are in a container, we do not want to create a virtual environment with poetry:
RUN poetry config virtualenvs.create true

# Install zsh shell:
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

# Copy using poetry.lock* in case it doesn't exist yet
COPY ./pyproject.toml ./poetry.lock* /usr/src/app/

# Install project dependencies
COPY . /usr/src/app

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

# Development Image
FROM base AS development

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV='true'

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

# Local Image
FROM development as local

# Set python verbose mode off in local environment:
ENV PYTHONVERBOSE 0

# Install szh shell:
RUN ["apt-get", "install", "-y", "zsh"]

# Install oh-my-zsh:
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions

# Install dev dependencies in local environment:
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi"

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #
```

**Comment by michealroberts** [comment] 2024-03-14 09:30
Ok @DavidVujic I am a little further in understanding this, it looks to me that the pythonpath needs to be set for pytest to understand what and where to do ...

Using this:

`pythonpath = "components"`

Inside the pyproject.toml file gives a successful run of the test suite, but how could this be extended to find all in components / bases / projects ... ? This is confusing.

**Comment by michealroberts** [comment] 2024-03-14 09:31
This goes back to my original issue that I raised as a discussion I think - I fundamentally think the structure you ascribe to is not great. tests should be co-located as best as possible imho ...

**Comment by DavidVujic** [comment] 2024-03-14 09:38
This is the first time I have heard about problems with the Python path and the discovery of the components folder, and my guess is that is has to do something with how it is setup in your Docker container. Are you developing inside docker?

When creating a virtual environment, and when you have the package includes setup, poetry will create a ".pth" file to discover the source code. This is the same as with a single-project setup and when using a "src" or a folder with the same name as the project.

If you would try out the example repo as-is on your machine, would the path discovery and pytest work for you?

**Comment by DavidVujic** [comment] 2024-03-14 09:44
@michealroberts  Why are you using `--no-root`? I think that might be the cause actually.

**Comment by DavidVujic** [comment] 2024-03-14 09:48
The `poetry install --no-root` option will not add the paths to the virtual environment, and that explains why the folders aren't discovered. During development, you would want to have the paths added and just run `poetry install`.

**Comment by DavidVujic** [comment] 2024-03-14 09:57
This hasn't much to do with Polylith, but how Poetry resolves paths.

If you would have a single-project repo (i.e. no Polylith) and put code into a `src` folder, you would run into the same issues:

```
pyproject.toml
src/
   hello/
      world.py
```

the pyproject.toml would need to know the structure as described in [their docs](https://python-poetry.org/docs/pyproject/#packages).

```
packages = [include = "hello", from = "src"} ]
```

when using the `--no-root` you will skip the part when Poetry adds the custom path(s) and probably not what you want to do when having the "src" structure or the Polylith structure.

**Comment by michealroberts** [comment] 2024-03-14 10:01
@DavidVujic I do indeed stand corrected, I assumed that poly was overriding this default path somehow. I shouldn't assume.

You're right on the --no-root flag inside the container, although that is the prescribed way of installing poetry in Docker within their documentation, this does not work well with this structure.

**Comment by DavidVujic** [comment] 2024-03-14 10:42
If you are using Docker as your dev environment, then it is probably not a good idea to do these kind of optimizations. I would recommend to develop directly on your machine, using a local virtual environment (that's what they are for, to isolate dependencies per dev "project"). But if you want to have your development environment inside a running Docker container, then you would need to have it dev-enabled.

The `--no-root` is not meant for development. Also, the `--no-root` will not work with any kind of structure that isn't according to the defaults, such as when using the "src" structure (quite common in Python projects). Having code in a monorepo wouldn't be the same as in a single-project.

Also, I strongly recommend to not have the multiproject or polylith plugins listed as project-depencencies (from looking at your pyproject.toml example). Poetry and its plugins should be installed according to the recommendations in the Poetry docs and also in the Polylith docs (using the `poetry self add <the-plugin-to-install>` command).

Otherwise, your project dependencies and the ones used by Poetry and/or the plugins might collide and not be compatible.

**Comment by DavidVujic** [comment] 2024-03-14 10:46
When __packaging & deploying__ something into __production__, you are not doing the copy step as Poetry suggests in their docs about CI and Docker. Please have a look in the [Polylith docs](https://davidvujic.github.io/python-polylith-docs/deployment/) about how to package a service (using the `build-project` command).

**Comment by michealroberts** [comment] 2024-03-14 11:20
The reason why we containerise development is to ensure consistency not only between python environments, but developer machines. What runs on one developer's machine might not run on another.

> When packaging & deploying something into production, you are not doing the copy step as Poetry suggests in their docs about CI and Docker. Please have a look in the [Polylith docs](https://davidvujic.github.io/python-polylith-docs/deployment/) about how to package a service (using the build-project command).

I'll make a mental note of that and be sure to follow the documentation.

RE: poetry plugins, I'll be sure to also amend this. I assumed that as we are using it as a project tool, in development, it should be installed to development dependencies. Otherwise ... how is this portable? 

Coming from other languages that have first class support for monorepos has been an eye opener on the conventions used by the python tooling ecosystem ... I wouldn't recommend doing what you're doing, but I would be happy to follow these "conventions". I would strongly argue that not installing tooling to dev dependencies could lead to a gap between team members.

**Comment by DavidVujic** [comment] 2024-03-14 11:35
The Poetry plugin feature is specifically for Poetry, and they recommend to install plugins using the `poetry self add` command. This, because Poetry has its own virtual environment with its own dependencies, separated from the environment the users have. This hasn't anything to do with monorepos, but how the Poetry plugin system is built.

If you develop in Docker, you still can have a project-specific virtual environment and a "global" environment. Global, within the container and a project-specific environment (usually a `.venv` folder). With this separation, you will have a dev-environment running in Docker in a similar way as having it on a local machine.

The plugins aren't something that is included in the production build of _your_ service or app. Poetry isn't either included in your service or app, these are tools that are used during development and in a CI to test & package things.

**Comment by michealroberts** [comment] 2024-03-14 11:39
Yes, so that's my point, why not install them to developer dependencies? They won't be included in the final built output, and this gives consistent tooling for the project.

My argument isn't the what or how, but the why. You need to deeply think about why you do something, and have it justified for what is best for both the software and the developers building it.

So far, the mental model and burden present just doesn't fit well imho.

If you have people asking what bases and components are, then you probably have your assumptions wrong on the what and the how.

**Comment by DavidVujic** [comment] 2024-03-14 11:39
There are alternatives to Poetry, such as Hatch and PDM. There's Polylith tooling for those ones too and they have a different take than Poetry on extending tooling (Hatch and PDM use build hooks instead of plugins).

**Comment by DavidVujic** [comment] 2024-03-14 11:46
> Yes, so that's my point, why not install them to developer dependencies? They won't be included in the final built output, and this gives consistent tooling for the project.

As I have tried to explain before, this is how __Poetry__ solves it, extending their tool with plugins and how to install them.

> My argument isn't the what or how, but the why. You need to deeply think about why you do something, and have it justified for what is best for both the software and the developers building it.
> 
> So far, the mental model and burden present just doesn't fit well imho.
> 
> If you have people asking what bases and components are, then you probably have your assumptions wrong on the what and the how.

There are various ways to accomplish code sharing in a Monorepo, or using a several-different repos approach and share code via installable libraries. Polylith has a different take on this thing. It's not that complex, having code in two folders (bases and components) is it?

**Comment by DavidVujic** [comment] 2024-03-14 12:13
I'll close this issue. I think this is an interesting conversation, but also think the issue is solved (the `--no-root` option). There is the `Discussions` forum at the [Polylith github](https://github.com/DavidVujic/python-polylith/discussions), where we could continue talk about the parts that aren't the traditional issues (i.e. things broken needed to to fix or problems to solve).

**Closed as completed by DavidVujic** 2024-03-14 12:13 UTC

**Comment by michealroberts** [comment] 2024-03-14 12:18
Happy to resolve also, I think there's a lot of strengths of this project and clearly a lot of thought has gone into it. So happy to amend my mental models.

Will sync up in discussions if we need anything else.
